site_name: Siddhi Testsuite ${_nameOfTestsuite}
site_description: Siddhi Testsuite ${_nameOfTestsuite} Extension
repo_name: Siddhi-Testsuite-${_nameOfTestsuite}
repo_url:
edit_url:
copyright:
theme:
  name: 'material'
  logo: images/siddhi-logo.svg
  favicon: images/favicon.ico
  palette:
    primary: teal
    accent: teal
extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/extra.js
extra:
  social:
google_analytics:
markdown_extensions:
  - markdown.extensions.admonition
pages:
  - Information : index.md
  - API Docs:
      - latest: api/latest.md
  - License: license.md
